<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\AdminController::create' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\AdminController::edit' => array('privates', '.service_locator.w2k0L9N', 'get_ServiceLocator_W2k0L9NService.php', true),
    'App\\Controller\\AdminController::remove' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\ContactController::index' => array('privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true),
    'App\\Controller\\SecurityController::registration' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\AdminController:create' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\AdminController:edit' => array('privates', '.service_locator.w2k0L9N', 'get_ServiceLocator_W2k0L9NService.php', true),
    'App\\Controller\\AdminController:remove' => array('privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true),
    'App\\Controller\\ContactController:index' => array('privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true),
    'App\\Controller\\SecurityController:registration' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
