<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEIR3LTu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEIR3LTu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEIR3LTu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEIR3LTu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEIR3LTu\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'EIR3LTu',
    'container.build_id' => 'b0c7fd30',
    'container.build_time' => 1547455641,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEIR3LTu');
